### PR TITLE
Controllers specs

### PR DESCRIPTION
**Pull request by davidigbo**
## In this pull request, Rspec test was implemented for users and posts controller actions following these steps:

- [ ] Add RSpec as a gem to your project.
- [ ] Create a Request spec file for all your controllers.
- [ ] Make sure that for each action you check:
- [ ] If the response status was correct.
- [ ] If a correct template was rendered.
- [ ] If the response body includes correct placeholder text.

### CODE REVIEW

**Review by DammyShittu — COMMENTED** [review]
Hi @david30-maker,

While you made a great effort in this project, I cannot proceed to review your code.

## Invalid Code Review Request

### On your readme menu headers, these links are not working: **`Video presentation`** and **`Deployment`**. Kindly fix them or remove them if you don't have any need for them.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by davidigbo** [comment]
@DammyShittu, thanks for pointing out those sections of the Readme file, it will be moved.

**Review by DammyShittu — APPROVED** [review]
Hi @david30-maker,

## APPROVED 🟢

## Highlights
✔️ Passing tests

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by davidigbo** [comment]
@DammyShittu, thanks for approving my project.

**Pull request merged**
